# Generated by Django 3.1.6 on 2021-02-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(max_length=32)),
                ('w_field', models.CharField(max_length=32)),
                ('w_phone', models.CharField(max_length=10)),
                ('w_age', models.IntegerField()),
                ('w_email', models.EmailField(max_length=254)),
                ('w_image', models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Ftrademark.eu%2Fteam%2Fpintz-associate-placeholder%2F&psig=AOvVaw1np7dteIwQekhimY1hEQKi&ust=1614228112495000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCKix2szage8CFQAAAAAdAAAAABAD', max_length=500)),
            ],
        ),
    ]
